---
- name: Docker Swarm init
  hosts: yc-instance-1
  gather_facts: Yes
  tasks:
    - name: Check if Swarm has already been init 
      shell: docker node ls
      register: swarm_status
      ignore_errors: true
      become: yes

    - name: Initialize Docker Swarm
      shell: >
            docker swarm init
            --advertise-addr={{ ansible_default_ipv4.address }}:2377
      when: swarm_status.rc != 0
      run_once: true
      become: yes



    - name: Get the worker join-token
      shell: docker swarm join-token --quiet worker
      register: worker_token
      become: yes


    - debug:
       msg: "{{ worker_token}}"




    - name: Add Workers to the Swarm
      shell: "docker swarm join --token {{ worker_token['stdout'] }} {{ ansible_default_ipv4.address }}:2377"
      run_once: true
      become: yes



