---
- name: Install docker on ya instance
  hosts: yc-instance-1
  gather_facts: Yes
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils  
        state: latest
      become: yes
        
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
      become: yes
 
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
      become: yes


    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
      become: yes




    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes


    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes




    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes




    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes




    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes




    - name: Check if Swarm has already been init
      shell: docker node ls
      register: swarm_status
      ignore_errors: true
      become: yes

    - name: Initialize Docker Swarm
      shell: >
            docker swarm init
            --advertise-addr={{ ansible_default_ipv4.address }}:2377
      when: swarm_status.rc != 0
      run_once: true
      become: yes



    - name: Get the worker join-token
      shell: docker swarm join-token --quiet worker
      register: worker_token
      become: yes





    - name: Add Workers to the Swarm
      shell: "docker swarm join --token {{ worker_token['stdout'] }} {{ ansible_default_ipv4.address }}:2377"
      run_once: true
      ignore_errors: true
      become: yes



