version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    restart: always
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres
    ports:
     - "10051:10051"       
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres
      - zabbix-server
    ports:
      - 8080:80
  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    privileged: true   #access mode for allowing resource access
    network_mode: "host"
    ports:
      - "10050:10050"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=127.0.0.1 #the IP/Dns of Zabbix server        
