- name: Deploy on Swarm Cluster
  hosts: yc-instance-1
  gather_facts: False
  tasks:
    - name: Create a directory
      file:
        path: /home/yc-user/deploy
        state: directory

    - name: Copy docker-compose-test.yml to master
      copy:
        src: docker-compose.yml
        dest: /home/yc-user/deploy

    - name: Deploy on Swarm
      shell: cd /home/yc-user/deploy && docker stack deploy -c docker-compose.yml zabbix
      register: stack_deploy
      become: yes

    - debug: var={{item}}
      with_items: stack_deploy.stdout_lines

    - name: Check list of services
      command: docker service ls
      register: service_list
      become: yes

    - debug: var={{item}}
      with_items: service_list.stdout_lines

    - name: Check list of stack
      command: docker stack ps zabbix
      register: stack_ps
      become: yes

    - debug: var={{item}}
      with_items: stack_ps.stdout_lines
